### ISSUE TITLE
"<<<<< HEAD " characters that blocks compilation

### ISSUE THREAD

**Issue by flexbeats** [luizhss/Android-Image-Classifier-App#1]
Hi,

I tried to build your app but I have those 

- "<<<<<<<HEAD" 
- "=======" 
- ">>>>>>> e9d7ca3dd6b69d9dde53cfe340fa70e4d6679598"

string lines that prevents compilation, can you remove them from source code please?
![image](https://user-images.githubusercontent.com/66123389/233661621-19b8190e-fccf-45a2-aa23-4d8a09dca600.png)

**Comment by luizhss** [comment]
Fixed! Sorry for the super late reply.

Thanks for pointing it out, it has been a while I don't work on this project. Sorry.
